### ISSUE TITLE
Create main model for line data

### ISSUE THREAD

**Issue by sanjuroj** [hackoregon/transportation-backend#14]
Create a model with four fields:
**date_range** - a postgres specific data type that may help with finding date overlaps
**data** - any non-date properties as an object (json might work but it should be compatible with the GeoFeatureModelSerializer from the django-rest-framework-gis
**source** - the name of the API where the data came from
**geom** - a geodjango line type

**Comment by sanjuroj** [comment]
see main Point model for an example

**Comment by saashimi** [comment]
Added a Line model, but just like the Point model, is really only applicable to CIP data.  Street permit line data is a bit different with respect to dates (instead of start of construction and end of construction, for example, street permit lines only have construction and warranty start dates). Also modified urls data to be able to access lines and points data.

**Comment by sanjuroj** [comment]
This looks good.  I don't think either Point or Line will be applicable to just the CIP data.  start date and end date may mean different things to different APIs but I think we can use whichever date feels closest to what we want for this map.  As the app matures, we may have to adjust of course.
